version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: library-postgres-container
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    restart: always